In [2]:
#1
import numpy as np

v = np.array([2., 2., 4.])


In [14]:
#2

a1 = np.array([[6, -9, 1], [4, 24, 8]])
res = 2 * a1
print(res)

a2 = np.array([[1, 0], [1, 0]])
res2 = a2@a1
print(res2)

a3 = np.array([list(range(i * 10, i * 10 + 6)) for i in range(6)])
print(a3[:, 1])
print(a3[1, 2:4])
print(a3[2:4, 4:6])
print(a3[2:5:2, 0:5:2])

[[ 12 -18   2]
 [  8  48  16]]
[[ 6 -9  1]
 [ 6 -9  1]]
[ 1 11 21 31 41 51]
[12 13]
[[24 25]
 [34 35]]
[[20 22 24]
 [40 42 44]]


In [6]:
#4
def swap_rows(M, a, b):
    ls = [num for num in M[a]]
    M[a] = M[b]
    M[b] = ls

def swap_cols(M, a, b):
    ls = [M[i][a] for i in range(len(M))]
    M[:, a] = M[:, b]
    M[:, b] = ls

a = np.array([[1, 2, 3], [3, 2, 1]])
swap_cols(a, 0, 1)
print(a)

[[2 1 3]
 [2 3 1]]


In [13]:
def set_array(L, rows, cols):
    a = np.empty((rows, cols))
    for i in range(rows):
        a[i] = L[cols*i:cols*(i+1)]
    return a

a = set_array([1, 2, 3, 4, 5, 6], 2, 3)
a

array([[1., 2., 3.],
       [4., 5., 6.]])